### ISSUE TITLE
Federation: API server does not allow privileged containers

### ISSUE THREAD

**Issue by irfanurrehman** [kubernetes/federation#15]
<a href="https://github.com/erikgrinaker"><img src="https://avatars2.githubusercontent.com/u/644420?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [erikgrinaker](https://github.com/erikgrinaker)**
_Tuesday Sep 12, 2017 at 14:14 GMT_
_Originally opened as https://github.com/kubernetes/kubernetes/issues/52341_

----

**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

Attempting to deploy a DaemonSet with `securityContext.privileged: true` in a federated cluster gives an error: `Forbidden: disallowed by cluster policy`

**What you expected to happen**:

The DaemonSet to be created.

**How to reproduce it (as minimally and precisely as possible)**:

Create a federated cluster using `kubefed`, and submit the following DaemonSet:

```yaml
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: privileged
  labels:
    app: privileged
spec:
  template:
    metadata:
      labels:
        app: privileged
    spec:
      containers:
      - name: privileged
        image: busybox
        command: ['sleep', '10000']
        securityContext:
          privileged: true
```

This gives the following error:

```sh
$ kubectl apply -f privileged.yaml
The DaemonSet "privileged" is invalid: spec.template.spec.containers[0].securityContext.privileged: Forbidden: disallowed by cluster policy
```
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.7.3
- Cloud provider or hardware configuration**: GKE
- OS (e.g. from /etc/os-release): COS 59 build 9460.73.0
- Kernel (e.g. `uname -a`): 4.4.52
- Install tools:
- Others: kubefed 1.7.3
