### ISSUE TITLE
Creating federated ingress only creates in single cluster

### ISSUE THREAD

**Issue by kinghrothgar** [kubernetes/federation#189]
**Kubernetes version** (use `kubectl version`): 
1.8.5-gke.0

**Environment**:

- **Cloud provider or hardware configuration**: 
GKE
- **OS** (e.g. from /etc/os-release): 
Container-Optimized OS from Google

**What happened**:
I am running a federated cluster in 4 regions. I ran `kubectl apply -f ing-hello-world.yaml --context production` where `production` is the federation context.

Contents of yaml file:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-world
  namespace: production
  annotations:
    kubernetes.io/ingress.class: "nginx"
  labels:
    app: hello-world
spec:
  rules:
  - host: hello.levenlabs.com
    http:
      paths:
      - path: /
        backend:
          serviceName: hello-world
          servicePort: 8080
```
An ingress is created in a random single cluster.  Each time I delete and re-run it, it ends up in a different single cluster.

**What you expected to happen**:
An ingress to be created in all federated clusters.

**How to reproduce it** (as minimally and precisely as possible):
Add a federated ingress with annotation `kubernetes.io/ingress.class: "nginx"`. I can fine no logs that imply anything went wrong.
