### ISSUE TITLE
HA Kubernetes etcd configuration

### ISSUE THREAD

**Issue by irfanurrehman** [kubernetes/federation#38]
<a href="https://github.com/justinsb"><img src="https://avatars2.githubusercontent.com/u/100893?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [justinsb](https://github.com/justinsb)**
_Saturday Jan 09, 2016 at 16:48 GMT_
_Originally opened as https://github.com/kubernetes/kubernetes/issues/19443_

----

I'm looking at setting up k8s with a HA master, and following along with the HA documentation at http://kubernetes.io/v1.1/docs/admin/high-availability.html

The k8s HA doc suggests using a discovery token.  However, the etcd documentation at https://github.com/coreos/etcd/blob/master/Documentation/clustering.md says:

> Moreover, discovery URLs should ONLY be used for the initial bootstrapping of a cluster. To change cluster membership after the cluster is already running, see the runtime reconfiguration guide.

I was thinking of running the masters in an AWS auto-scaling group, but this means that their IP addresses would change (I have some strategies involving grabbing disks to ensure that they have some notion of persistent identity though).

An alternative idea I had was to use static config, but to have a process that queried the cloud API, and located the instances, and then dynamically updated a hosts file with the IP addresses.  So for example etcd would be launched with

```
etcd -name node1 -initial-advertise-peer-urls http://10.0.1.10:2380 \
  -listen-peer-urls http://10.0.1.10:2380 \
  -listen-client-urls http://10.0.1.10:2379 \
  -advertise-client-urls http://10.0.1.10:2379 \
  -initial-cluster-token etcd-cluster-1 \
  -initial-cluster node1=http://node1:2380,node2=http://node2:2380,node3=http://node3:2380 \
  -initial-cluster-state new
```

And then the hosts file would look like

```
10.0.1.10 node1 
10.0.1.11 node2
# node3 not yet running
```

(I guess I could also use skydns rather than hosts files, but I am not sure about the bootstrapping there.  Or even Route53...)

Will discovery actually work and 'self-heal' as IP addresses change?  Is there a better alternative to dynamically updating DNS / host files?  @xiang90 I think you would know best here.

Also cc @quinton-hoole because I think you'll find this interesting...

**Comment by irfanurrehman** [comment]
<a href="https://github.com/quinton-hoole"><img src="https://avatars0.githubusercontent.com/u/10390785?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [quinton-hoole](https://github.com/quinton-hoole)**
_Saturday Jan 09, 2016 at 18:31 GMT_

----

Hi Justin

More on Monday, but for now...
1. I think that we decided to implement self-healing first, and only do high availability later?  In the former case, you don't need any of this, as you can have just one etcd server, and a static IP?
2. Assuming that you do actually need a quorum etc as you mention above, you can either use multiple static IP's, or DNS names.  See below for an example DNS-based configuration that I tested:

```
apiVersion: v1
kind: ReplicationController
metadata:
#  labels:
#    run: my-etcd-1
  name: my-etcd-1
#  namespace: default
spec:
#  replicas: 1
#  selector:
#    run: my-etcd-1
  template:
    metadata:
      labels:
        run: my-etcd-1
    spec:
      containers:
      - env:
        - name: ETCD_NAME
          value: my-etcd-1
        - name: ETCD_DISCOVERY_SRV
          value: test.ubernetes.io
        - name: ETCD_INITIAL_ADVERTISE_PEER_URLS
          value: http://my-etcd-1.test.ubernetes.io:2380
        - name: ETCD_INITIAL_CLUSTER_TOKEN
          value: etcd-cluster-quinton-01
        - name: ETCD_INITIAL_CLUSTER_STATE
          value: new      
        - name: ETCD_ADVERTISE_CLIENT_URLS
          value: http://my-etcd-1.test.ubernetes.io:2379
        - name: ETCD_LISTEN_CLIENT_URLS
          value: http://0.0.0.0:2379
        - name: ETCD_LISTEN_PEER_URLS
          value: http://0.0.0.0:2380
        image: quay.io/coreos/etcd:v2.2.0
        name: my-etcd-1
        ports:
        - containerPort: 2379
          protocol: TCP
        - containerPort: 2380
          protocol: TCP
```

**Comment by irfanurrehman** [comment]
<a href="https://github.com/quinton-hoole"><img src="https://avatars0.githubusercontent.com/u/10390785?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [quinton-hoole](https://github.com/quinton-hoole)**
_Saturday Jan 09, 2016 at 18:32 GMT_

----

```
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    run: my-etcd-2
  name: my-etcd-2
  namespace: default
spec:
  replicas: 1
  selector:
    run: my-etcd-2
  template:
    metadata:
      labels:
        run: my-etcd-2
    spec:
      containers:
      - env:
        - name: ETCD_NAME
          value: my-etcd-2
        - name: ETCD_DISCOVERY_SRV
          value: test.ubernetes.io
        - name: ETCD_INITIAL_ADVERTISE_PEER_URLS
          value: http://my-etcd-2.test.ubernetes.io:2380
        - name: ETCD_INITIAL_CLUSTER_TOKEN
          value: etcd-cluster-quinton-01
        - name: ETCD_INITIAL_CLUSTER_STATE
          value: new      
        - name: ETCD_ADVERTISE_CLIENT_URLS
          value: http://my-etcd-2.test.ubernetes.io:2379
        - name: ETCD_LISTEN_CLIENT_URLS
          value: http://0.0.0.0:2379
        - name: ETCD_LISTEN_PEER_URLS
          value: http://0.0.0.0:2380
        image: quay.io/coreos/etcd:v2.2.0
        name: my-etcd-2
        ports:
        - containerPort: 2379
          protocol: TCP
        - containerPort: 2380
          protocol: TCP
```

etc...
